"""Per-host Telegram button chrome.

Telegram only paints inline buttons primary (blue), success (green), or
danger (red). https://core.telegram.org/bots/api#inlinekeyboardbutton

Each host therefore keeps that color and swaps the emoji kit so Mira’s
lab desk does not look like Theo’s HUD.
"""

from __future__ import annotations

DEFAULT_BUTTONS = {
    "prep": "🛠️ Prep",
    "team": "📅 Team",
    "crew": "📸 Crew",
    "sheet": "📄 Sheet",
    "order": "🛒 Order",
    "menu": "⬅️ Menu",
    "email": "📧 Email",
    "debit": "💳 Debit",
    "vegas": "✅ Vegas",
    "not_lv": "📍 Not LV",
    "next": "🔁 Next teammate",
    "rotate": "🔁 Rotate again",
    "pick": "👥 Pick a favorite",
    "qty1": "1",
    "qty2": "2",
    "qty3": "3",
}

# Action words stay the same. Emoji kit follows the host’s style.
KITS: dict[str, dict[str, str]] = {
    "theo": {
        "prep": "⚡ Prep",
        "team": "🖥️ Team",
        "crew": "📡 Crew",
        "sheet": "📟 Sheet",
        "menu": "⚡ Menu",
        "email": "⚡ Email",
        "next": "⚡ Next",
        "rotate": "⚡ Again",
        "pick": "⚡ Pick",
        "qty1": "⚡ 1",
        "qty2": "⚡ 2",
        "qty3": "⚡ 3",
    },
    "mira": {
        "prep": "🧬 Prep",
        "team": "🥼 Team",
        "crew": "🔬 Crew",
        "sheet": "📋 Sheet",
        "menu": "🧬 Menu",
        "email": "🧬 Email",
        "next": "🧬 Next",
        "rotate": "🧬 Again",
        "pick": "🧬 Pick",
        "qty1": "🧬 1",
        "qty2": "🧬 2",
        "qty3": "🧬 3",
    },
    "sol": {
        "prep": "☀️ Prep",
        "team": "☕ Team",
        "crew": "🌅 Crew",
        "sheet": "🌤️ Sheet",
        "menu": "☀️ Menu",
        "email": "☀️ Email",
        "next": "☀️ Next",
        "rotate": "☀️ Again",
        "pick": "☀️ Pick",
        "qty1": "☀️ 1",
        "qty2": "☀️ 2",
        "qty3": "☀️ 3",
    },
    "nova": {
        "prep": "🚀 Prep",
        "team": "🌙 Team",
        "crew": "🌌 Crew",
        "sheet": "🛰️ Sheet",
        "menu": "🚀 Menu",
        "email": "🚀 Email",
        "next": "🚀 Next",
        "rotate": "🚀 Again",
        "pick": "🚀 Pick",
        "qty1": "🚀 1",
        "qty2": "🚀 2",
        "qty3": "🚀 3",
    },
    "reed": {
        "prep": "📋 Prep",
        "team": "☎️ Team",
        "crew": "🗂️ Crew",
        "sheet": "📎 Sheet",
        "menu": "📋 Menu",
        "email": "📋 Email",
        "next": "📋 Next",
        "rotate": "📋 Again",
        "pick": "📋 Pick",
        "qty1": "📋 1",
        "qty2": "📋 2",
        "qty3": "📋 3",
    },
    "lila": {
        "prep": "🌸 Prep",
        "team": "💐 Team",
        "crew": "🎀 Crew",
        "sheet": "💌 Sheet",
        "menu": "🌸 Menu",
        "email": "🌸 Email",
        "next": "🌸 Next",
        "rotate": "🌸 Again",
        "pick": "🌸 Pick",
        "qty1": "🌸 1",
        "qty2": "🌸 2",
        "qty3": "🌸 3",
    },
    "kai": {
        "prep": "🌊 Prep",
        "team": "🏄 Team",
        "crew": "🏖️ Crew",
        "sheet": "🐚 Sheet",
        "menu": "🌊 Menu",
        "email": "🌊 Email",
        "next": "🌊 Next",
        "rotate": "🌊 Again",
        "pick": "🌊 Pick",
        "qty1": "🌊 1",
        "qty2": "🌊 2",
        "qty3": "🌊 3",
    },
    "sage": {
        "prep": "🌿 Prep",
        "team": "🍵 Team",
        "crew": "🍃 Crew",
        "sheet": "📖 Sheet",
        "menu": "🌿 Menu",
        "email": "🌿 Email",
        "next": "🌿 Next",
        "rotate": "🌿 Again",
        "pick": "🌿 Pick",
        "qty1": "🌿 1",
        "qty2": "🌿 2",
        "qty3": "🌿 3",
    },
    "vega": {
        "prep": "✨ Prep",
        "team": "💜 Team",
        "crew": "🌟 Crew",
        "sheet": "💖 Sheet",
        "menu": "✨ Menu",
        "email": "✨ Email",
        "next": "✨ Next",
        "rotate": "✨ Again",
        "pick": "✨ Pick",
        "qty1": "✨ 1",
        "qty2": "✨ 2",
        "qty3": "✨ 3",
    },
    "orion": {
        "prep": "🛡️ Prep",
        "team": "📻 Team",
        "crew": "🛰️ Crew",
        "sheet": "📁 Sheet",
        "menu": "🛡️ Menu",
        "email": "🛡️ Email",
        "next": "🛡️ Next",
        "rotate": "🛡️ Again",
        "pick": "🛡️ Pick",
        "qty1": "🛡️ 1",
        "qty2": "🛡️ 2",
        "qty3": "🛡️ 3",
    },
    "wynn": {
        "prep": "🎯 Prep",
        "team": "📞 Team",
        "crew": "👥 Crew",
        "sheet": "📑 Sheet",
        "menu": "🎯 Menu",
        "email": "🎯 Email",
        "next": "🎯 Next",
        "rotate": "🎯 Again",
        "pick": "🎯 Pick",
        "qty1": "🎯 1",
        "qty2": "🎯 2",
        "qty3": "🎯 3",
    },
    "indi": {
        "prep": "🎨 Prep",
        "team": "🖌️ Team",
        "crew": "🌈 Crew",
        "sheet": "🖍️ Sheet",
        "menu": "🎨 Menu",
        "email": "🎨 Email",
        "next": "🎨 Next",
        "rotate": "🎨 Again",
        "pick": "🎨 Pick",
        "qty1": "🎨 1",
        "qty2": "🎨 2",
        "qty3": "🎨 3",
    },
    "pax": {
        "prep": "🕊️ Prep",
        "team": "🤍 Team",
        "crew": "🤝 Crew",
        "sheet": "📝 Sheet",
        "menu": "🕊️ Menu",
        "email": "🕊️ Email",
        "next": "🕊️ Next",
        "rotate": "🕊️ Again",
        "pick": "🕊️ Pick",
        "qty1": "🕊️ 1",
        "qty2": "🕊️ 2",
        "qty3": "🕊️ 3",
    },
    "ember": {
        "prep": "🔥 Prep",
        "team": "☎️ Team",
        "crew": "🌋 Crew",
        "sheet": "📛 Sheet",
        "menu": "🔥 Menu",
        "email": "🔥 Email",
        "next": "🔥 Next",
        "rotate": "🔥 Again",
        "pick": "🔥 Pick",
        "qty1": "🔥 1",
        "qty2": "🔥 2",
        "qty3": "🔥 3",
    },
    "quinn": {
        "prep": "🧭 Prep",
        "team": "🗺️ Team",
        "crew": "📍 Crew",
        "sheet": "📌 Sheet",
        "menu": "🧭 Menu",
        "email": "🧭 Email",
        "next": "🧭 Next",
        "rotate": "🧭 Again",
        "pick": "🧭 Pick",
        "qty1": "🧭 1",
        "qty2": "🧭 2",
        "qty3": "🧭 3",
    },
    "nori": {
        "prep": "🍃 Prep",
        "team": "🌱 Team",
        "crew": "🪴 Crew",
        "sheet": "📗 Sheet",
        "menu": "🍃 Menu",
        "email": "🍃 Email",
        "next": "🍃 Next",
        "rotate": "🍃 Again",
        "pick": "🍃 Pick",
        "qty1": "🍃 1",
        "qty2": "🍃 2",
        "qty3": "🍃 3",
    },
    "dash": {
        "prep": "⏱️ Prep",
        "team": "📞 Team",
        "crew": "🏁 Crew",
        "sheet": "📶 Sheet",
        "menu": "⏱️ Menu",
        "email": "⏱️ Email",
        "next": "⏱️ Next",
        "rotate": "⏱️ Again",
        "pick": "⏱️ Pick",
        "qty1": "⏱️ 1",
        "qty2": "⏱️ 2",
        "qty3": "⏱️ 3",
    },
    "halo": {
        "prep": "💫 Prep",
        "team": "✨ Team",
        "crew": "🌟 Crew",
        "sheet": "📒 Sheet",
        "menu": "💫 Menu",
        "email": "💫 Email",
        "next": "💫 Next",
        "rotate": "💫 Again",
        "pick": "💫 Pick",
        "qty1": "💫 1",
        "qty2": "💫 2",
        "qty3": "💫 3",
    },
    "rio": {
        "prep": "🌵 Prep",
        "team": "🏜️ Team",
        "crew": "🌞 Crew",
        "sheet": "🗺️ Sheet",
        "menu": "🌵 Menu",
        "email": "🌵 Email",
        "next": "🌵 Next",
        "rotate": "🌵 Again",
        "pick": "🌵 Pick",
        "qty1": "🌵 1",
        "qty2": "🌵 2",
        "qty3": "🌵 3",
    },
    "true": {
        "prep": "🏛️ Prep",
        "team": "👔 Team",
        "crew": "🏠 Crew",
        "sheet": "📜 Sheet",
        "menu": "🏛️ Menu",
        "email": "🏛️ Email",
        "next": "🏛️ Next",
        "rotate": "🏛️ Again",
        "pick": "🏛️ Pick",
        "qty1": "🏛️ 1",
        "qty2": "🏛️ 2",
        "qty3": "🏛️ 3",
    },
}
